package org.inria.dmsp.schema;

// ////////////////////////////////////////////////// 
// // CODE AFTER THAT IS GENERATED BY QEPGenerator // 
// ////////////////////////////////////////////////// 

// This is the set of SQL queries used to generate EP_UI.java 
// Note that : 
//   - EP generation fails (bug...) when altogether, must be generated by query type  
//   - EP generation for queries marked by x is buggy and must be corrected by hand 

// NB: to be able to quickly build the java file, a header is placed at the  
// beginning of the file and should be removed from the output. 
// --> Replace "//JAVA " by "" in the output. 

// Bugs: 
// buggy plans are tagged with "TODO"  
// --> those plans must be corrected manually 

public class EP_UI {

	  /*  TODO (FOR OPTIM):
		   *  o	EP_QUERY_AC_SELECT_EVENT_INFO_COMMENT_BY_FORM_BETWEEN_DATEEVENT		--> Optimization query for "Tableau de bord"
		   *  o	EP_QUERY_AC_SELECT_ INFOnoc_BY_FORM									--> Optimization query for "calendrier"
		   *  o	EP_QUERY_AC_SELECT_ INFO_pos_num_BY_FORM							--> Optimization query for "Plan d'aide"
		   *  o	EP_QUERY_NOAC_SELECT_nom_prenom_type_tel_idglobal_USER				--> Optimization query for "Liste des Intervenants"
		   *  o	EP_QUERY_NOAC_SELECT_USER_civilite_nom_prenom_BY_IDGLOBAL			--> Optimization query for "Fiche de synthèse - référent user"
		   *  TODO (REQUIRED):
		   *  o EP_QUERY_AC_SELECT_INFO_BY_EVENT_AND_FILTRE							--> Optimization query for "Fiche de synthèse - référent entourage"
		   *  o EP_QUERY_AC_SELECT_INFO_valnum_BY_EVENT_AND_POSITION				--> Optimization query for "Fiche de synthèse - GIR"

		   */

// liste de l'entourage (Info.Filtre=? pour récupérer les infos nom, prénom, lien => pas de comment) 
// NB: identique à EP_QUERY_AC_SELECT_INFO_BY_FILTRE avec en + le champs IdUser 
public static String EP_QUERY_AC_SELECT_USER_EVENT_INFO_BY_FILTRE = 
/* SQL : 	SELECT i.Position, i.ValChar, i.ValNum, i.IdEvent, i.ValDate, i.IdComment, i.TSSPT, e.IdUser FROM Event e, Info i WHERE i.Idevent=e.IdGlobal AND i.Filtre=?; */
"/*EP \u0001 " + 
"0 5 5 4 # " + /* SCAN, Table Info (4) -->R0 */
"1 4 4 5 r0 7 4 1 45 42 43 44 41 38 46 # " + /* TABLE_LOOKUP pos:R0, 7 cols, table Info(4), is_table: 1	-->R1 - R7 */
"4 3 3 4 46 0 ?1 r7 # " + /* SELECT, att: Filtre(46), comparator: 0, parameter: ?1 (R8), from pos: R7*/
"1 2 2 3 r0 4 1 0 1 0 2 3 # " + /* TABLE_LOOKUP pos:R0, 4 cols, skt SktInfo(1), is_table: 0  -->R9 - R12 */
"8 1 1 2 0 r9 r10 r11 # " + /* ACCESS_RIGHTS access_type: 0 (0-s,1-u,2-d,3-i) res_user:R9 res_form:R10 res_epis:R11 */
"1 0 0 1 r12 2 3 1 28 33 # " + /* TABLE_LOOKUP pos:R12, 2 cols, table Event(3), is_table: 1	-->R13 - R14 */
"\u0000 8 1 1 Position 0 2 ValChar 1 3 ValNum 1 13 IdEvent 2 4 ValDate 1 5 IdComment 1 6 TSSPT 1 14 IdUser # " + /* META_RESULT, 8 cols, type(0-char 1-num 2-date) [out_result name] */
"\u0000*/";


// liste des fiches de liaison (Info.Filtre=? pour récupérer les infos Date, Type, Origine, Cat. Prof., Obs. => un comment) 
// NB: identique à EP_QUERY_AC_SELECT_INFO_BY_FILTRE avec en + le champs IdUser, et l'accès au comment (=> valcomment à la place de IdComment) 
public static String EP_QUERY_AC_SELECT_USER_EVENT_INFO_COMMENT_BY_FILTRE = 
/* SQL : 	SELECT i.Position, i.ValChar, i.ValNum, i.IdEvent, i.ValDate, i.TSSPT, e.IdUser, c.ValComment FROM Event e, Info i, Comment c WHERE i.Idevent=e.IdGlobal AND i.IdComment=c.IdGlobal AND i.Filtre=?;	 */
"/*EP \u0001 " + 
"0 6 6 4 # " + /* SCAN, Table Info (4) -->R0 */
"1 5 5 6 r0 6 4 1 45 42 43 44 38 46 # " + /* TABLE_LOOKUP pos:R0, 6 cols, table Info(4), is_table: 1	-->R1 - R6 */
"4 4 4 5 46 0 ?1 r6 # " + /* SELECT, att: Filtre(46), comparator: 0, parameter: ?1 (R7), from pos: R6*/
"1 3 3 4 r0 5 1 0 1 0 2 3 4 # " + /* TABLE_LOOKUP pos:R0, 5 cols, skt SktInfo(1), is_table: 0  -->R8 - R12 */
"8 2 2 3 0 r8 r9 r10 # " + /* ACCESS_RIGHTS access_type: 0 (0-s,1-u,2-d,3-i) res_user:R8 res_form:R9 res_epis:R10 */
"1 1 1 2 r11 2 3 1 28 33 # " + /* TABLE_LOOKUP pos:R11, 2 cols, table Event(3), is_table: 1	-->R13 - R14 */
"1 0 0 1 r12 1 5 1 51 # " + /* TABLE_LOOKUP pos:R12, 1 cols, table Comment(5), is_table: 1	-->R15 - R15 */
"\u0000 8 1 1 Position 0 2 ValChar 1 3 ValNum 1 13 IdEvent 2 4 ValDate 1 5 TSSPT 1 14 IdUser 0 15 ValComment # " + /* META_RESULT, 8 cols, type(0-char 1-num 2-date) [out_result name] */
"\u0000*/";


// liste des fiches de liaison (Info.Filtre=? pour récupérer les infos Date, Type, Origine, Cat. Prof., Obs. => un comment) 
// NB: identique à EP_QUERY_AC_SELECT_USER_EVENT_INFO_COMMENT_BY_FILTRE avec en + un critère d'intervalle sur la date de l'event 
public static String EP_QUERY_AC_SELECT_USER_EVENT_INFO_COMMENT_BY_FILTRE_BETWEEN_DATEEVENT = 
/* SQL : 	SELECT i.Position, i.ValChar, i.ValNum, i.IdEvent, i.ValDate, i.TSSPT, e.IdUser, c.ValComment FROM Event e, Info i, Comment c WHERE i.Idevent=e.IdGlobal AND i.IdComment=c.IdGlobal AND i.Filtre=? AND e.DateEvent>? AND e.DateEvent<?; */
"/*EP \u0003 " + 
"0 8 8 4 # " + /* SCAN, Table Info (4) -->R0 */
"1 7 7 8 r0 6 4 1 45 42 43 44 38 46 # " + /* TABLE_LOOKUP pos:R0, 6 cols, table Info(4), is_table: 1	-->R1 - R6 */
"4 6 6 7 46 0 ?1 r6 # " + /* SELECT, att: Filtre(46), comparator: 0, parameter: ?1 (R7), from pos: R6*/
"1 5 5 6 r0 5 1 0 1 0 2 3 4 # " + /* TABLE_LOOKUP pos:R0, 5 cols, skt SktInfo(1), is_table: 0  -->R8 - R12 */
"8 4 4 5 0 r8 r9 r10 # " + /* ACCESS_RIGHTS access_type: 0 (0-s,1-u,2-d,3-i) res_user:R8 res_form:R9 res_epis:R10 */
"1 3 3 4 r11 3 3 1 28 33 35 # " + /* TABLE_LOOKUP pos:R11, 3 cols, table Event(3), is_table: 1	-->R13 - R15 */
"4 2 2 3 35 1 ?2 r15 # " + /* SELECT, att: DateEvent(35), comparator: 1, parameter: ?2 (R16), from pos: R15*/
"4 1 1 2 35 2 ?3 r15 # " + /* SELECT, att: DateEvent(35), comparator: 2, parameter: ?3 (R17), from pos: R15*/
"1 0 0 1 r12 1 5 1 51 # " + /* TABLE_LOOKUP pos:R12, 1 cols, table Comment(5), is_table: 1	-->R18 - R18 */
"\u0000 8 1 1 Position 0 2 ValChar 1 3 ValNum 1 13 IdEvent 2 4 ValDate 1 5 TSSPT 1 14 IdUser 0 18 ValComment # " + /* META_RESULT, 8 cols, type(0-char 1-num 2-date) [out_result name] */
"\u0000*/";


// Optimization query for the "tableau de bord" ==> OK 
// We add the form table for optimization ... 
public static String EP_QUERY_AC_SELECT_EVENT_INFO_COMMENT_BY_FORM_BETWEEN_DATEEVENT = 
/* SQL : 	SELECT i.IdGlobal, i.Position, i.ValChar, i.ValDate, i.ValNum, i.IdEvent, c.ValComment FROM event e, info i, comment c, Formulaire f WHERE i.IdEvent=e.IdGlobal and i.IdComment=c.IdGlobal and e.IdForm = f.IdGlobal and f.IdGlobal=? and e.DateEvent > ? and e.DateEvent < ? */
"/*EP \u0003 " + 
"0 9 9 4 # " + /* SCAN, Table Info (4) -->R0 */
"1 8 8 9 r0 5 1 0 1 0 2 4 3 # " + /* TABLE_LOOKUP pos:R0, 5 cols, skt SktInfo(1), is_table: 0  -->R1 - R5 */
"8 7 7 8 0 r1 r2 r3 # " + /* ACCESS_RIGHTS access_type: 0 (0-s,1-u,2-d,3-i) res_user:R1 res_form:R2 res_epis:R3 */
"1 6 6 7 r2 1 1 1 5 # " + /* TABLE_LOOKUP pos:R2, 1 cols, table Formulaire(1), is_table: 1	-->R6 - R6 */
"4 5 5 6 5 0 ?1 r6 # " + /* SELECT, att: IdGlobal(5), comparator: 0, parameter: ?1 (R7), from pos: R6*/
"1 4 4 5 r5 1 3 1 35 # " + /* TABLE_LOOKUP pos:R5, 1 cols, table Event(3), is_table: 1	-->R8 - R8 */
"4 3 3 4 35 1 ?2 r8 # " + /* SELECT, att: DateEvent(35), comparator: 1, parameter: ?2 (R9), from pos: R8*/
"4 2 2 3 35 2 ?3 r8 # " + /* SELECT, att: DateEvent(35), comparator: 2, parameter: ?3 (R10), from pos: R8*/
"1 1 1 2 r0 6 4 1 36 45 42 44 43 40 # " + /* TABLE_LOOKUP pos:R0, 6 cols, table Info(4), is_table: 1	-->R11 - R16 */
"1 0 0 1 r4 1 5 1 51 # " + /* TABLE_LOOKUP pos:R4, 1 cols, table Comment(5), is_table: 1	-->R17 - R17 */
"\u0000 7 1 11 IdGlobal 1 12 Position 0 13 ValChar 2 14 ValDate 1 15 ValNum 1 16 IdEvent 0 17 ValComment # " + /* META_RESULT, 7 cols, type(0-char 1-num 2-date) [out_result name] */
"\u0000*/";


// Optimization query for the "calendrier" ==> OK 
// Should replace EP_QUERY_AC_SELECT_EVENT_INFO_COMMENT_BY_FORM_AND_FILTRE 
// Un des infoDM repéré par son concept indique dans quel cas on est : 
// (1) case du calendrier (2) note de bas de page 
// Dans tous les cas, pas besoin de comments   
// We add the form table for optimization ...  
public static String EP_QUERY_AC_SELECT_INFOnoc_BY_FORM =  
/* SQL : 	SELECT i.IdEvent, i.Position, i.ValChar, i.ValDate, i.ValNum FROM event e, info i, formulaire f WHERE i.IdEvent=e.IdGlobal and e.IdForm = f.IdGlobal and f.IdGlobal=? */
"/*EP \u0001 " + 
"0 5 5 4 # " + /* SCAN, Table Info (4) -->R0 */
"1 4 4 5 r0 3 1 0 1 0 2 # " + /* TABLE_LOOKUP pos:R0, 3 cols, skt SktInfo(1), is_table: 0  -->R1 - R3 */
"8 3 3 4 0 r1 r2 r3 # " + /* ACCESS_RIGHTS access_type: 0 (0-s,1-u,2-d,3-i) res_user:R1 res_form:R2 res_epis:R3 */
"1 2 2 3 r2 1 1 1 5 # " + /* TABLE_LOOKUP pos:R2, 1 cols, table Formulaire(1), is_table: 1	-->R4 - R4 */
"4 1 1 2 5 0 ?1 r4 # " + /* SELECT, att: IdGlobal(5), comparator: 0, parameter: ?1 (R5), from pos: R4*/
"1 0 0 1 r0 5 4 1 40 45 42 44 43 # " + /* TABLE_LOOKUP pos:R0, 5 cols, table Info(4), is_table: 1	-->R6 - R10 */
"\u0000 5 1 6 IdEvent 1 7 Position 0 8 ValChar 2 9 ValDate 1 10 ValNum # " + /* META_RESULT, 5 cols, type(0-char 1-num 2-date) [out_result name] */
"\u0000*/";


// Optimization query for the "Plan d'aide"==> OK 
// Special version of EP_QUERY_AC_SELECT_EVENT_INFO_BY_FORM projecting only position and valnum 
// We add the form table for optimization ...  
public static String EP_QUERY_AC_SELECT_INFO_pos_num_BY_FORM =  
/* SQL : 	SELECT I.Position, I.ValNum FROM info I, event E, formulaire F WHERE I.IdEvent = E.IdGlobal and E.IdForm = F.IdGlobal AND F.IdGlobal = ? */
"/*EP \u0001 " + 
"0 5 5 4 # " + /* SCAN, Table Info (4) -->R0 */
"1 4 4 5 r0 3 1 0 1 0 2 # " + /* TABLE_LOOKUP pos:R0, 3 cols, skt SktInfo(1), is_table: 0  -->R1 - R3 */
"8 3 3 4 0 r1 r2 r3 # " + /* ACCESS_RIGHTS access_type: 0 (0-s,1-u,2-d,3-i) res_user:R1 res_form:R2 res_epis:R3 */
"1 2 2 3 r2 1 1 1 5 # " + /* TABLE_LOOKUP pos:R2, 1 cols, table Formulaire(1), is_table: 1	-->R4 - R4 */
"4 1 1 2 5 0 ?1 r4 # " + /* SELECT, att: IdGlobal(5), comparator: 0, parameter: ?1 (R5), from pos: R4*/
"1 0 0 1 r0 2 4 1 45 43 # " + /* TABLE_LOOKUP pos:R0, 2 cols, table Info(4), is_table: 1	-->R6 - R7 */
"\u0000 2 1 6 Position 1 7 ValNum # " + /* META_RESULT, 2 cols, type(0-char 1-num 2-date) [out_result name] */
"\u0000*/";


// Optimization query for the "Liste des Intervenants" ==> OK 
// Version of EP_QUERY_NOAC_SELECT_USER projecting only useful fields 
public static String EP_QUERY_NOAC_SELECT_nom_prenom_type_tel_idglobal_USER =  
/* SQL : 	SELECT Nom, Prenom, Type, Tel, IdGlobal FROM UserDMSP */
"/*EP \u0000 " + 
"0 1 1 2 # " + /* SCAN, Table UserDMSP (2) -->R0 */
"1 0 0 1 r0 5 2 1 14 19 15 23 10 # " + /* TABLE_LOOKUP pos:R0, 5 cols, table UserDMSP(2), is_table: 1	-->R1 - R5 */
"\u0000 5 0 1 Nom 0 2 Prenom 1 3 Type 0 4 Tel 1 5 IdGlobal # " + /* META_RESULT, 5 cols, type(0-char 1-num 2-date) [out_result name] */
"\u0000*/";


// Optimization query for the "Fiche de synthèse - référent user" ==> OK 
// Version of EP_QUERY_NOAC_SELECT_USER_BY_ID  projecting only useful fields 
public static String EP_QUERY_NOAC_SELECT_USER_civilite_nom_prenom_BY_IDGLOBAL =  
/* SQL : 	SELECT Civilite, Nom, Prenom FROM UserDMSP u WHERE u.IdGlobal = ? */
"/*EP \u0001 " + 
"2 1 1 -1 4 ?1 # " + /* CI_LOOKUP ref_tab:UserDMSP(2) key_col_id:10 ka_id:4	 key:?1(R0) -->R1 */
"1 0 0 1 r1 3 2 1 18 14 19 # " + /* TABLE_LOOKUP pos:R1, 3 cols, table UserDMSP(2), is_table: 1	-->R2 - R4 */
"\u0000 3 1 2 Civilite 0 3 Nom 0 4 Prenom # " + /* META_RESULT, 3 cols, type(0-char 1-num 2-date) [out_result name] */
"\u0000*/";


// Optimization query for the "Fiche de synthèse - référent entourage"==> OK 
// Special version of EP_QUERY_AC_SELECT_EVENT_INFO_COMMENT_BY_EVENT projecting only useful fields 
// The filter (Filtre) should indicate the useful fields for the query (civilite, nom, prenom) 
// Valnum for civilité ???? 
public static String EP_QUERY_AC_SELECT_INFO_BY_EVENT_AND_FILTRE =  
/* SQL : 	SELECT i.Position, i.ValChar, i.ValNum FROM Event e, Info i WHERE i.IdEvent=e.IdGlobal and e.IdGlobal=? and i.Filtre = ? */
"/*EP \u0002 " + 
"0 6 6 4 # " + /* SCAN, Table Info (4) -->R0 */
"1 5 5 6 r0 4 4 1 45 42 43 46 # " + /* TABLE_LOOKUP pos:R0, 4 cols, table Info(4), is_table: 1	-->R1 - R4 */
"4 4 4 5 46 0 ?2 r4 # " + /* SELECT, att: Filtre(46), comparator: 0, parameter: ?2 (R5), from pos: R4*/
"1 3 3 4 r0 4 1 0 1 0 2 3 # " + /* TABLE_LOOKUP pos:R0, 4 cols, skt SktInfo(1), is_table: 0  -->R6 - R9 */
"8 2 2 3 0 r6 r7 r8 # " + /* ACCESS_RIGHTS access_type: 0 (0-s,1-u,2-d,3-i) res_user:R6 res_form:R7 res_epis:R8 */
"1 1 1 2 r9 1 3 1 28 # " + /* TABLE_LOOKUP pos:R9, 1 cols, table Event(3), is_table: 1	-->R10 - R10 */
"4 0 0 1 28 0 ?1 r10 # " + /* SELECT, att: IdGlobal(28), comparator: 0, parameter: ?1 (R11), from pos: R10*/
"\u0000 3 1 1 Position 0 2 ValChar 1 3 ValNum # " + /* META_RESULT, 3 cols, type(0-char 1-num 2-date) [out_result name] */
"\u0000*/";


// Optimization query for the "Fiche de synthèse - GIR" ==> OK 
// We add the event table for optimization ... 
public static final String EP_QUERY_AC_SELECT_INFO_valnum_BY_EVENT_AND_POSITION =  
/* SQL : 	SELECT i.ValNum FROM Event e, Info i WHERE i.IdEvent=e.IdGlobal and e.IdGlobal=? and i.Position = ? */
"/*EP \u0002 " + 
"0 6 6 4 # " + /* SCAN, Table Info (4) -->R0 */
"1 5 5 6 r0 2 4 1 43 45 # " + /* TABLE_LOOKUP pos:R0, 2 cols, table Info(4), is_table: 1	-->R1 - R2 */
"4 4 4 5 45 0 ?2 r2 # " + /* SELECT, att: Position(45), comparator: 0, parameter: ?2 (R3), from pos: R2*/
"1 3 3 4 r0 4 1 0 1 0 2 3 # " + /* TABLE_LOOKUP pos:R0, 4 cols, skt SktInfo(1), is_table: 0  -->R4 - R7 */
"8 2 2 3 0 r4 r5 r6 # " + /* ACCESS_RIGHTS access_type: 0 (0-s,1-u,2-d,3-i) res_user:R4 res_form:R5 res_epis:R6 */
"1 1 1 2 r7 1 3 1 28 # " + /* TABLE_LOOKUP pos:R7, 1 cols, table Event(3), is_table: 1	-->R8 - R8 */
"4 0 0 1 28 0 ?1 r8 # " + /* SELECT, att: IdGlobal(28), comparator: 0, parameter: ?1 (R9), from pos: R8*/
"\u0000 1 1 1 ValNum # " + /* META_RESULT, 1 cols, type(0-char 1-num 2-date) [out_result name] */
"\u0000*/";


//  LOGIN: 
//  EP_QUERY_NOAC_SELECT_USER_BY_CERTIF 
//  EP_QUERY_NOAC_SELECT_HABILITATION_BY_IDUSER 
// x EP_QUERY_AC_SELECT_AUTHORIZED_INSERT_FORM   
// SELECT PLANS: 
//  EP_QUERY_NOAC_SELECT_EVENT_FORM_USER_BY_FILTRE 
//  EP_QUERY_AC_SELECT_EVENT_FORM_USER_BY_FILTRE 
// 	EP_QUERY_NOAC_SELECT_EVENT_INFO_COMMENT_BY_FORM 
// 	EP_QUERY_AC_SELECT_EVENT_INFO_COMMENT_BY_FORM 	 
// 	EP_QUERY_NOAC_SELECT_USER_BY_ID			 
// 	EP_QUERY_AC_SELECT_EVENT_INFO_COMMENT_BY_EVENT	 
// 	EP_QUERY_AC_SELECT_INFO_BY_FILTRE		 
// 	EP_QUERY_NOAC_SELECT_USER_BY_INFOLEGALE 
// 	EP_QUERY_NOAC_SELECT_USER 
// 	EP_QUERY_AC_SELECT_EVENT_INFO_COMMENT_BY_FORM_AND_FILTRE  
// 	EP_QUERY_AC_SELECT_EVENT_INFO_COMMENT_BY_FORM_AND_FILTRE_FROM_EVENT 
// 	EP_QUERY_AC_SELECT_EVENT_INFO_BY_FORM_AND_DATE  	 
// 	EP_QUERY_AC_SELECT_EVENT_INFO_COMMENT_BY_EVENT_AND_CONCEPT  
//  EP_QUERY_AC_SELECT_EVENT_BY_ID 
//  EP_QUERY_NOAC_SELECT_HABILITATION 
// 	EP_QUERY_AC_SELECT_EVENT_INFO_BY_FORM 
// 	EP_QUERY_AC_SELECT_EVENT_INFO_BY_FORM_AND_POSITION 
//  EP_QUERY_SELECT_USER_HABILITATION 
// 	EP_QUERY_AC_SELECT_INFO_valnum_BY_EVENT_AND_POSITION 
// INSERT PLANS: 
// x OEP_EVENT_AC_INSERT 
// x OEP_INFO_AC_INSERT 
// x OEP_COMMENT_NOAC_INSERT 
// x EP_HABILITATION_NOAC_INSERT 
// 	EP_DELETED_NOAC_INSERT 

// UPDATE PLANS: 
//  INFO_AC_UPDATE_BY_ID 
// x COMMENT_AC_UPDATE_BY_ID 
//  EVENT_AC_UPDATE_BY_ID 
// DELETE PLANS: 
//  EP_HABILITATION_NOAC_DELETE_BY_USER 
//  

// ########## 
//   LOGIN: # 
// ########## 

public static String EP_QUERY_AC_SELECT_INFO_BY_FORM=
/* SQL : 	SELECT i.IdGlobal, i.Position, i.IdEvent, i.IdConcept, i.ValChar, i.ValDate, i.ValNum, i.IdComment FROM Event e, Info i WHERE i.IdEvent = e.IdGlobal AND e.IdForm = ? */
"/*EP \u0001 " + 
"0 5 5 4 # " + /* SCAN, Table Info (4) -->R0 */
"1 4 4 5 r0 4 1 0 1 0 2 3 # " + /* TABLE_LOOKUP pos:R0, 4 cols, skt SktInfo(1), is_table: 0  -->R1 - R4 */
"8 3 3 4 0 r1 r2 r3 # " + /* ACCESS_RIGHTS access_type: 0 (0-s,1-u,2-d,3-i) res_user:R1 res_form:R2 res_epis:R3 */
"1 2 2 3 r4 1 3 1 32 # " + /* TABLE_LOOKUP pos:R4, 1 cols, table Event(3), is_table: 1	-->R5 - R5 */
"4 1 1 2 32 0 ?1 r5 # " + /* SELECT, att: IdForm(32), comparator: 0, parameter: ?1 (R6), from pos: R5*/
"1 0 0 1 r0 8 4 1 36 45 40 92 42 44 43 41 # " + /* TABLE_LOOKUP pos:R0, 8 cols, table Info(4), is_table: 1	-->R7 - R14 */
"\u0000 8 1 7 IdGlobal 1 8 Position 1 9 IdEvent 1 10 IdConcept 0 11 ValChar 2 12 ValDate 1 13 ValNum 1 14 IdComment # " + /* META_RESULT, 8 cols, type(0-char 1-num 2-date) [out_result name] */
"\u0000*/";


public static String EP_QUERY_NOAC_SELECT_USER_BY_CERTIF = 
/* SQL : 	SELECT IdGlobal, IdRole, Nom, Prenom FROM UserDMSP WHERE Certificate = ?; */
"/*EP \u0001 " + 
"0 2 2 2 # " + /* SCAN, Table UserDMSP (2) -->R0 */
"1 1 1 2 r0 5 2 1 10 93 14 19 27 # " + /* TABLE_LOOKUP pos:R0, 5 cols, table UserDMSP(2), is_table: 1	-->R1 - R5 */
"4 0 0 1 27 0 ?1 r5 # " + /* SELECT, att: Certificate(27), comparator: 0, parameter: ?1 (R6), from pos: R5*/
"\u0000 4 1 1 IdGlobal 1 2 IdRole 0 3 Nom 0 4 Prenom # " + /* META_RESULT, 4 cols, type(0-char 1-num 2-date) [out_result name] */
"\u0000*/";


public static String EP_QUERY_NOAC_SELECT_HABILITATION_BY_IDUSER = 
/* SQL : 	SELECT IdRole FROM Habilitation WHERE IdUser = ?; */
"/*EP \u0001 " + 
"0 2 2 8 # " + /* SCAN, Table Habilitation (8) -->R0 */
"1 1 1 2 r0 2 8 1 62 63 # " + /* TABLE_LOOKUP pos:R0, 2 cols, table Habilitation(8), is_table: 1	-->R1 - R2 */
"4 0 0 1 63 0 ?1 r2 # " + /* SELECT, att: IdUser(63), comparator: 0, parameter: ?1 (R3), from pos: R2*/
"\u0000 1 1 1 IdRole # " + /* META_RESULT, 1 cols, type(0-char 1-num 2-date) [out_result name] */
"\u0000*/";


public static String EP_QUERY_AC_SELECT_AUTHORIZED_INSERT_FORM = 
//SELECT F.IdGlobal FROM Formulaire F, UserDMSP U, Episode E WHERE U.Idintern = ? AND E.IdIntern = ?; 
//--> not supported  
// TODO (DONE): do it by hand (see org.inria.dmsp.EP_UI)  
// from org.inria.dmsp.EP_UI :
"/*EP \u0002 " +
"0 8 8 0 # " +  // SCAN, Table EPISODE(0) --> r0 (pos_ep)
"4 7 7 8 0 0 ?1 r0 # " +   // SELECT, Att IdGlobal(0) BUT SHOULD BE ID_INTERN !!!, equal (0),// value ?1 (in r1), with value in r0 --> r1 (pos_ep=?1)
"0 6 6 2 # " +    // SCAN, Table USER(2) --> r2 (pos_us)
"4 5 5 6 10 0 ?2 r2 # " +   // SELECT, Att IdGlobal(10) BUT SHOULD BE ID_INTERN !!!, equal (0),// value ?2 (in r3), with value in r2 --> r3 (pos_us=?2)
"0 3 3 1 # " +    // SCAN, Table FORM(1) --> r4 (pos_fo)
"7 4 4 5 7 # " + // FLOW
"7 2 2 3 4 # " + // FLOW
"8 1 1 2 3 r2 r4 r0 # " +   // ACCESS_RIGHTS INSERT (3), USER (r2), FORM (r4), EPISODE (r0)
"1 0 0 1 r4 1 1 1 5 # " +   // TABLE_LOOKUP, Pos r4, 1 col, Table FORM(1), a TABLE(1), IDG(5)// --> r5 (Form.IdGlobal)
"\u0000 1 1 5 IdGlobal # \u0000*/";   // 1 col, Type Number(1), Pos r5, Name IdForm
//"\u0000 4 1 4 IdForm 1 2 IdUser 1 0 IdEpisode 1 5 IdGlobal # \u0000*/";   // 1 col, Type Number(1), Pos r5, Name IdForm


// ################# 
//   SELECT PLANS: # 
// ################# 

public static String EP_QUERY_NOAC_SELECT_EVENT_FORM_USER_BY_FILTRE = 
/* SQL : 	SELECT u.Nom, e.DateEvent,e.IdGlobal eIdGlobal, f.IdGlobal fIdGlobal,u.IdGlobal uIdGlobal,   e.TSSPT FROM UserDMSP u, Event e, Formulaire f WHERE f.idGlobal = e.idForm AND u.idGlobal = e.idUser AND f.Filtre = ? */
"/*EP \u0001 " + 
"0 5 5 3 # " + /* SCAN, Table Event (3) -->R0 */
"1 4 4 5 r0 2 0 0 1 0 # " + /* TABLE_LOOKUP pos:R0, 2 cols, skt SktEvent(0), is_table: 0  -->R1 - R2 */
"1 3 3 4 r2 2 1 1 5 94 # " + /* TABLE_LOOKUP pos:R2, 2 cols, table Formulaire(1), is_table: 1	-->R3 - R4 */
"4 2 2 3 94 0 ?1 r4 # " + /* SELECT, att: Filtre(94), comparator: 0, parameter: ?1 (R5), from pos: R4*/
"1 1 1 2 r1 2 2 1 14 10 # " + /* TABLE_LOOKUP pos:R1, 2 cols, table UserDMSP(2), is_table: 1	-->R6 - R7 */
"1 0 0 1 r0 3 3 1 35 28 30 # " + /* TABLE_LOOKUP pos:R0, 3 cols, table Event(3), is_table: 1	-->R8 - R10 */
"\u0000 6 0 6 Nom 2 8 DateEvent 1 9 eIdGlobal 1 3 fIdGlobal 1 7 uIdGlobal 1 10 TSSPT # " + /* META_RESULT, 6 cols, type(0-char 1-num 2-date) [out_result name] */
"\u0000*/";


public static String EP_QUERY_AC_SELECT_EVENT_FORM_USER_BY_FILTRE = 
/* SQL : 	SELECT u.Nom, e.DateEvent,e.IdGlobal eIdGlobal, f.IdGlobal fIdGlobal,u.IdGlobal uIdGlobal,   e.TSSPT FROM UserDMSP u, Event e, Formulaire f WHERE f.idGlobal = e.idForm AND u.idGlobal = e.idUser AND f.Filtre = ? */
"/*EP \u0001 " + 
"0 6 6 3 # " + /* SCAN, Table Event (3) -->R0 */
"1 5 5 6 r0 3 0 0 1 0 2 # " + /* TABLE_LOOKUP pos:R0, 3 cols, skt SktEvent(0), is_table: 0  -->R1 - R3 */
"8 4 4 5 0 r1 r2 r3 # " + /* ACCESS_RIGHTS access_type: 0 (0-s,1-u,2-d,3-i) res_user:R1 res_form:R2 res_epis:R3 */
"1 3 3 4 r2 2 1 1 5 94 # " + /* TABLE_LOOKUP pos:R2, 2 cols, table Formulaire(1), is_table: 1	-->R4 - R5 */
"4 2 2 3 94 0 ?1 r5 # " + /* SELECT, att: Filtre(94), comparator: 0, parameter: ?1 (R6), from pos: R5*/
"1 1 1 2 r1 2 2 1 14 10 # " + /* TABLE_LOOKUP pos:R1, 2 cols, table UserDMSP(2), is_table: 1	-->R7 - R8 */
"1 0 0 1 r0 3 3 1 35 28 30 # " + /* TABLE_LOOKUP pos:R0, 3 cols, table Event(3), is_table: 1	-->R9 - R11 */
"\u0000 6 0 7 Nom 2 9 DateEvent 1 10 eIdGlobal 1 4 fIdGlobal 1 8 uIdGlobal 1 11 TSSPT # " + /* META_RESULT, 6 cols, type(0-char 1-num 2-date) [out_result name] */
"\u0000*/";


public static String EP_QUERY_NOAC_SELECT_EVENT_INFO_COMMENT_BY_FORM = 
/* SQL : 	SELECT i.IdGlobal, i.Position, i.ValChar, i.ValDate, i.ValNum, c.ValComment FROM Event e, Info i, Comment c WHERE i.IdEvent = e.IdGlobal AND i.IdComment = c.IdGlobal AND e.IdForm=?; */
"/*EP \u0001 " + 
"0 5 5 4 # " + /* SCAN, Table Info (4) -->R0 */
"1 4 4 5 r0 2 1 0 4 3 # " + /* TABLE_LOOKUP pos:R0, 2 cols, skt SktInfo(1), is_table: 0  -->R1 - R2 */
"1 3 3 4 r2 1 3 1 32 # " + /* TABLE_LOOKUP pos:R2, 1 cols, table Event(3), is_table: 1	-->R3 - R3 */
"4 2 2 3 32 0 ?1 r3 # " + /* SELECT, att: IdForm(32), comparator: 0, parameter: ?1 (R4), from pos: R3*/
"1 1 1 2 r0 5 4 1 36 45 42 44 43 # " + /* TABLE_LOOKUP pos:R0, 5 cols, table Info(4), is_table: 1	-->R5 - R9 */
"1 0 0 1 r1 1 5 1 51 # " + /* TABLE_LOOKUP pos:R1, 1 cols, table Comment(5), is_table: 1	-->R10 - R10 */
"\u0000 6 1 5 IdGlobal 1 6 Position 0 7 ValChar 2 8 ValDate 1 9 ValNum 0 10 ValComment # " + /* META_RESULT, 6 cols, type(0-char 1-num 2-date) [out_result name] */
"\u0000*/";


public static String EP_QUERY_AC_SELECT_EVENT_INFO_COMMENT_BY_FORM  = 
/* SQL : 	SELECT i.IdGlobal, i.Position, i.ValChar, i.ValDate, i.ValNum, c.ValComment FROM Event e, Info i, Comment c WHERE i.IdEvent = e.IdGlobal AND i.IdComment = c.IdGlobal AND e.IdForm=?; */
"/*EP \u0001 " + 
"0 6 6 4 # " + /* SCAN, Table Info (4) -->R0 */
"1 5 5 6 r0 5 1 0 1 0 2 4 3 # " + /* TABLE_LOOKUP pos:R0, 5 cols, skt SktInfo(1), is_table: 0  -->R1 - R5 */
"8 4 4 5 0 r1 r2 r3 # " + /* ACCESS_RIGHTS access_type: 0 (0-s,1-u,2-d,3-i) res_user:R1 res_form:R2 res_epis:R3 */
"1 3 3 4 r5 1 3 1 32 # " + /* TABLE_LOOKUP pos:R5, 1 cols, table Event(3), is_table: 1	-->R6 - R6 */
"4 2 2 3 32 0 ?1 r6 # " + /* SELECT, att: IdForm(32), comparator: 0, parameter: ?1 (R7), from pos: R6*/
"1 1 1 2 r0 5 4 1 36 45 42 44 43 # " + /* TABLE_LOOKUP pos:R0, 5 cols, table Info(4), is_table: 1	-->R8 - R12 */
"1 0 0 1 r4 1 5 1 51 # " + /* TABLE_LOOKUP pos:R4, 1 cols, table Comment(5), is_table: 1	-->R13 - R13 */
"\u0000 6 1 8 IdGlobal 1 9 Position 0 10 ValChar 2 11 ValDate 1 12 ValNum 0 13 ValComment # " + /* META_RESULT, 6 cols, type(0-char 1-num 2-date) [out_result name] */
"\u0000*/";


public static String EP_QUERY_AC_SELECT_EVENT_INFO_COMMENT_BY_EVENT = 
/* SQL : 	SELECT i.IdGlobal, i.Position, i.ValChar, i.ValDate, i.ValNum, c.ValComment, e.DateFin FROM Event e, Info i, Comment c WHERE i.IdEvent = e.IdGlobal AND i.IdComment = c.IdGlobal AND e.IdGlobal=? */
"/*EP \u0001 " + 
"0 6 6 4 # " + /* SCAN, Table Info (4) -->R0 */
"1 5 5 6 r0 5 1 0 1 0 2 4 3 # " + /* TABLE_LOOKUP pos:R0, 5 cols, skt SktInfo(1), is_table: 0  -->R1 - R5 */
"8 4 4 5 0 r1 r2 r3 # " + /* ACCESS_RIGHTS access_type: 0 (0-s,1-u,2-d,3-i) res_user:R1 res_form:R2 res_epis:R3 */
"1 3 3 4 r5 2 3 1 95 28 # " + /* TABLE_LOOKUP pos:R5, 2 cols, table Event(3), is_table: 1	-->R6 - R7 */
"4 2 2 3 28 0 ?1 r7 # " + /* SELECT, att: IdGlobal(28), comparator: 0, parameter: ?1 (R8), from pos: R7*/
"1 1 1 2 r0 5 4 1 36 45 42 44 43 # " + /* TABLE_LOOKUP pos:R0, 5 cols, table Info(4), is_table: 1	-->R9 - R13 */
"1 0 0 1 r4 1 5 1 51 # " + /* TABLE_LOOKUP pos:R4, 1 cols, table Comment(5), is_table: 1	-->R14 - R14 */
"\u0000 7 1 9 IdGlobal 1 10 Position 0 11 ValChar 2 12 ValDate 1 13 ValNum 0 14 ValComment 2 6 DateFin # " + /* META_RESULT, 7 cols, type(0-char 1-num 2-date) [out_result name] */
"\u0000*/";


public static String EP_QUERY_NOAC_SELECT_USER_BY_ID = 
/* SQL : 	SELECT Nom, Type, Responsable, Identifiant, Civilite, Prenom, Adresse, CodePost, Ville, Tel, Mobile, Courriel, InfoLegale, IdRole FROM UserDMSP WHERE IdGlobal = ?; */
"/*EP \u0001 " + 
"2 1 1 -1 4 ?1 # " + /* CI_LOOKUP ref_tab:UserDMSP(2) key_col_id:10 ka_id:4	 key:?1(R0) -->R1 */
"1 0 0 1 r1 14 2 1 14 15 16 17 18 19 20 22 21 23 24 25 26 93 # " + /* TABLE_LOOKUP pos:R1, 14 cols, table UserDMSP(2), is_table: 1	-->R2 - R15 */
"\u0000 14 0 2 Nom 1 3 Type 0 4 Responsable 0 5 Identifiant 1 6 Civilite 0 7 Prenom 0 8 Adresse 0 9 CodePost 0 10 Ville 0 11 Tel 0 12 Mobile 0 13 Courriel 1 14 InfoLegale 1 15 IdRole # " + /* META_RESULT, 14 cols, type(0-char 1-num 2-date) [out_result name] */
"\u0000*/";


public static String EP_QUERY_AC_SELECT_INFO_BY_FILTRE =
/* SQL : 	SELECT Position, ValChar, ValNum, IdEvent, ValDate, IdComment, TSSPT FROM Info WHERE Filtre=?; */
"/*EP \u0001 " + 
"0 4 4 4 # " + /* SCAN, Table Info (4) -->R0 */
"1 3 3 4 r0 8 4 1 45 42 43 40 44 41 38 46 # " + /* TABLE_LOOKUP pos:R0, 8 cols, table Info(4), is_table: 1	-->R1 - R8 */
"4 2 2 3 46 0 ?1 r8 # " + /* SELECT, att: Filtre(46), comparator: 0, parameter: ?1 (R9), from pos: R8*/
"1 1 1 2 r0 3 1 0 1 0 2 # " + /* TABLE_LOOKUP pos:R0, 3 cols, skt SktInfo(1), is_table: 0  -->R10 - R12 */
"8 0 0 1 0 r10 r11 r12 # " + /* ACCESS_RIGHTS access_type: 0 (0-s,1-u,2-d,3-i) res_user:R10 res_form:R11 res_epis:R12 */
"\u0000 7 1 1 Position 0 2 ValChar 1 3 ValNum 1 4 IdEvent 2 5 ValDate 1 6 IdComment 1 7 TSSPT # " + /* META_RESULT, 7 cols, type(0-char 1-num 2-date) [out_result name] */
"\u0000*/";


public static String EP_QUERY_NOAC_SELECT_USER_BY_INFOLEGALE = 
/* SQL : 	SELECT IdGlobal, Nom, Type, Identifiant, Civilite, Prenom, Tel, Mobile, IdRole, Ville FROM UserDMSP WHERE infolegale=?; */
"/*EP \u0001 " + 
"0 2 2 2 # " + /* SCAN, Table UserDMSP (2) -->R0 */
"1 1 1 2 r0 11 2 1 10 14 15 17 18 19 23 24 93 21 26 # " + /* TABLE_LOOKUP pos:R0, 11 cols, table UserDMSP(2), is_table: 1	-->R1 - R11 */
"4 0 0 1 26 0 ?1 r11 # " + /* SELECT, att: InfoLegale(26), comparator: 0, parameter: ?1 (R12), from pos: R11*/
"\u0000 10 1 1 IdGlobal 0 2 Nom 1 3 Type 0 4 Identifiant 1 5 Civilite 0 6 Prenom 0 7 Tel 0 8 Mobile 1 9 IdRole 0 10 Ville # " + /* META_RESULT, 10 cols, type(0-char 1-num 2-date) [out_result name] */
"\u0000*/";


public static final String EP_QUERY_NOAC_SELECT_USER = 
/* SQL : 	SELECT IdGlobal, Nom, Type, Identifiant, Civilite, Prenom, Tel, Mobile, IdRole, Ville FROM UserDMSP; */
"/*EP \u0000 0 1 1 2 # 1 0 0 1 r0 10 2 1 10 14 15 17 18 19 23 24 93 21 # \u0000 10 1 1 IdGlobal 0 2 Nom 1 3 Type 0 4 Identifiant 1 5 Civilite 0 6 Prenom 0 7 Tel 0 8 Mobile 1 9 IdRole 0 10 Ville # \u0000*/";


public static String EP_QUERY_AC_SELECT_EVENT_INFO_COMMENT_BY_FORM_AND_FILTRE = 
/* SQL : 	SELECT e.IdGlobal IdEvent, i.Position, i.ValChar, i.ValDate, i.ValNum, c.ValComment FROM Event e, Info i, Comment c  WHERE i.IdEvent = e.IdGlobal AND i.IdComment = c.IdGlobal AND e.IdForm=? AND i.Filtre = ?; */
"/*EP \u0002 " + 
"0 7 7 4 # " + /* SCAN, Table Info (4) -->R0 */
"1 6 6 7 r0 6 4 1 40 45 42 44 43 46 # " + /* TABLE_LOOKUP pos:R0, 6 cols, table Info(4), is_table: 1	-->R1 - R6 */
"4 5 5 6 46 0 ?2 r6 # " + /* SELECT, att: Filtre(46), comparator: 0, parameter: ?2 (R7), from pos: R6*/
"1 4 4 5 r0 5 1 0 1 0 2 4 3 # " + /* TABLE_LOOKUP pos:R0, 5 cols, skt SktInfo(1), is_table: 0  -->R8 - R12 */
"8 3 3 4 0 r8 r9 r10 # " + /* ACCESS_RIGHTS access_type: 0 (0-s,1-u,2-d,3-i) res_user:R8 res_form:R9 res_epis:R10 */
"1 2 2 3 r12 1 3 1 32 # " + /* TABLE_LOOKUP pos:R12, 1 cols, table Event(3), is_table: 1	-->R13 - R13 */
"4 1 1 2 32 0 ?1 r13 # " + /* SELECT, att: IdForm(32), comparator: 0, parameter: ?1 (R14), from pos: R13*/
"1 0 0 1 r11 1 5 1 51 # " + /* TABLE_LOOKUP pos:R11, 1 cols, table Comment(5), is_table: 1	-->R15 - R15 */
"\u0000 6 1 1 IdEvent 1 2 Position 0 3 ValChar 2 4 ValDate 1 5 ValNum 0 15 ValComment # " + /* META_RESULT, 6 cols, type(0-char 1-num 2-date) [out_result name] */
"\u0000*/";


public static final String EP_QUERY_AC_SELECT_EVENT_INFO_COMMENT_BY_FORM_AND_FILTRE_FROM_EVENT =
/* SQL : 	SELECT e.IdGlobal, i.Position, i.ValChar, i.ValDate, i.ValNum, c.ValComment FROM Event e, Info i, Comment c  WHERE i.IdEvent = e.IdGlobal AND i.IdComment = c.IdGlobal AND e.IdForm=? AND e.Filtre = ?; */
"/*EP \u0002 " + 
"0 7 7 4 # " + /* SCAN, Table Info (4) -->R0 */
"1 6 6 7 r0 5 1 0 1 0 2 4 3 # " + /* TABLE_LOOKUP pos:R0, 5 cols, skt SktInfo(1), is_table: 0  -->R1 - R5 */
"8 5 5 6 0 r1 r2 r3 # " + /* ACCESS_RIGHTS access_type: 0 (0-s,1-u,2-d,3-i) res_user:R1 res_form:R2 res_epis:R3 */
"1 4 4 5 r5 2 3 1 32 96 # " + /* TABLE_LOOKUP pos:R5, 2 cols, table Event(3), is_table: 1	-->R6 - R7 */
"4 3 3 4 32 0 ?1 r6 # " + /* SELECT, att: IdForm(32), comparator: 0, parameter: ?1 (R8), from pos: R6*/
"4 2 2 3 96 0 ?2 r7 # " + /* SELECT, att: Filtre(96), comparator: 0, parameter: ?2 (R9), from pos: R7*/
"1 1 1 2 r0 5 4 1 40 45 42 44 43 # " + /* TABLE_LOOKUP pos:R0, 5 cols, table Info(4), is_table: 1	-->R10 - R14 */
"1 0 0 1 r4 1 5 1 51 # " + /* TABLE_LOOKUP pos:R4, 1 cols, table Comment(5), is_table: 1	-->R15 - R15 */
"\u0000 6 1 10 IdGlobal 1 11 Position 0 12 ValChar 2 13 ValDate 1 14 ValNum 0 15 ValComment # " + /* META_RESULT, 6 cols, type(0-char 1-num 2-date) [out_result name] */
"\u0000*/";


public static String EP_QUERY_AC_SELECT_EVENT_INFO_BY_FORM_AND_DATE =
/* SQL : 	SELECT I.ValChar, I.ValNum, I.ValDate, I.Position, I.TSSPT, E.DateFin, E.IdGlobal IdEvent, E.IdUser FROM Info I, Event E WHERE I.IdEvent = E.IdGlobal AND E.IdForm=? AND E.DateFin>?; */
"/*EP \u0002 " + 
"0 6 6 4 # " + /* SCAN, Table Info (4) -->R0 */
"1 5 5 6 r0 4 1 0 1 0 2 3 # " + /* TABLE_LOOKUP pos:R0, 4 cols, skt SktInfo(1), is_table: 0  -->R1 - R4 */
"8 4 4 5 0 r1 r2 r3 # " + /* ACCESS_RIGHTS access_type: 0 (0-s,1-u,2-d,3-i) res_user:R1 res_form:R2 res_epis:R3 */
"1 3 3 4 r4 3 3 1 95 33 32 # " + /* TABLE_LOOKUP pos:R4, 3 cols, table Event(3), is_table: 1	-->R5 - R7 */
"4 2 2 3 32 0 ?1 r7 # " + /* SELECT, att: IdForm(32), comparator: 0, parameter: ?1 (R8), from pos: R7*/
"4 1 1 2 95 1 ?2 r5 # " + /* SELECT, att: DateFin(95), comparator: 1, parameter: ?2 (R9), from pos: R5*/
"1 0 0 1 r0 6 4 1 42 43 44 45 38 40 # " + /* TABLE_LOOKUP pos:R0, 6 cols, table Info(4), is_table: 1	-->R10 - R15 */
"\u0000 8 0 10 ValChar 1 11 ValNum 2 12 ValDate 1 13 Position 1 14 TSSPT 2 5 DateFin 1 15 IdEvent 1 6 IdUser # " + /* META_RESULT, 8 cols, type(0-char 1-num 2-date) [out_result name] */
"\u0000*/";


public static String EP_QUERY_AC_SELECT_EVENT_INFO_BY_FORM_SINGLEEVENT =
/* SQL : 	SELECT I.ValChar, I.ValNum, I.ValDate, I.Position FROM Info I, Event E WHERE I.IdEvent = E.IdGlobal AND E.IdForm=?; */
"/*EP \u0001 " + 
"0 5 5 4 # " + /* SCAN, Table Info (4) -->R0 */
"1 4 4 5 r0 4 1 0 1 0 2 3 # " + /* TABLE_LOOKUP pos:R0, 4 cols, skt SktInfo(1), is_table: 0  -->R1 - R4 */
"8 3 3 4 0 r1 r2 r3 # " + /* ACCESS_RIGHTS access_type: 0 (0-s,1-u,2-d,3-i) res_user:R1 res_form:R2 res_epis:R3 */
"1 2 2 3 r4 1 3 1 32 # " + /* TABLE_LOOKUP pos:R4, 1 cols, table Event(3), is_table: 1	-->R5 - R5 */
"4 1 1 2 32 0 ?1 r5 # " + /* SELECT, att: IdForm(32), comparator: 0, parameter: ?1 (R6), from pos: R5*/
"1 0 0 1 r0 4 4 1 42 43 44 45 # " + /* TABLE_LOOKUP pos:R0, 4 cols, table Info(4), is_table: 1	-->R7 - R10 */
"\u0000 4 0 7 ValChar 1 8 ValNum 2 9 ValDate 1 10 Position # " + /* META_RESULT, 4 cols, type(0-char 1-num 2-date) [out_result name] */
"\u0000*/";


public static String EP_QUERY_AC_SELECT_EVENT_INFO_COMMENT_BY_EVENT_AND_CONCEPT = 
/* SQL : 	SELECT i.Position, c.ValComment FROM Info i, Comment c, Event e WHERE e.IdGlobal = i.IdEvent AND i.IdComment = c.IdGlobal AND e.Idglobal=? AND i.IdConcept=? */
"/*EP \u0002 " + 
"0 7 7 4 # " + /* SCAN, Table Info (4) -->R0 */
"1 6 6 7 r0 2 4 1 45 92 # " + /* TABLE_LOOKUP pos:R0, 2 cols, table Info(4), is_table: 1	-->R1 - R2 */
"4 5 5 6 92 0 ?2 r2 # " + /* SELECT, att: IdConcept(92), comparator: 0, parameter: ?2 (R3), from pos: R2*/
"1 4 4 5 r0 5 1 0 1 0 2 4 3 # " + /* TABLE_LOOKUP pos:R0, 5 cols, skt SktInfo(1), is_table: 0  -->R4 - R8 */
"8 3 3 4 0 r4 r5 r6 # " + /* ACCESS_RIGHTS access_type: 0 (0-s,1-u,2-d,3-i) res_user:R4 res_form:R5 res_epis:R6 */
"1 2 2 3 r8 1 3 1 28 # " + /* TABLE_LOOKUP pos:R8, 1 cols, table Event(3), is_table: 1	-->R9 - R9 */
"4 1 1 2 28 0 ?1 r9 # " + /* SELECT, att: IdGlobal(28), comparator: 0, parameter: ?1 (R10), from pos: R9*/
"1 0 0 1 r7 1 5 1 51 # " + /* TABLE_LOOKUP pos:R7, 1 cols, table Comment(5), is_table: 1	-->R11 - R11 */
"\u0000 2 1 1 Position 0 11 ValComment # " + /* META_RESULT, 2 cols, type(0-char 1-num 2-date) [out_result name] */
"\u0000*/";


public static String EP_QUERY_AC_SELECT_EVENT_BY_ID = 
/* SQL : 	SELECT DateFin FROM Event WHERE IdGlobal = ?; */
"/*EP \u0001 " + 
"2 3 3 -1 5 ?1 # " + /* CI_LOOKUP ref_tab:Event(3) key_col_id:28 ka_id:5	 key:?1(R0) -->R1 */
"1 2 2 3 r1 3 0 0 1 0 2 # " + /* TABLE_LOOKUP pos:R1, 3 cols, skt SktEvent(0), is_table: 0  -->R2 - R4 */
"8 1 1 2 0 r2 r3 r4 # " + /* ACCESS_RIGHTS access_type: 0 (0-s,1-u,2-d,3-i) res_user:R2 res_form:R3 res_epis:R4 */
"1 0 0 1 r1 1 3 1 95 # " + /* TABLE_LOOKUP pos:R1, 1 cols, table Event(3), is_table: 1	-->R5 - R5 */
"\u0000 1 2 5 DateFin # " + /* META_RESULT, 1 cols, type(0-char 1-num 2-date) [out_result name] */
"\u0000*/";


public static String EP_QUERY_NOAC_SELECT_HABILITATION =  
/* SQL : 	SELECT IdUser,IdGlobal FROM habilitation; */
"/*EP \u0000 " + 
"0 1 1 8 # " + /* SCAN, Table Habilitation (8) -->R0 */
"1 0 0 1 r0 2 8 1 63 57 # " + /* TABLE_LOOKUP pos:R0, 2 cols, table Habilitation(8), is_table: 1	-->R1 - R2 */
"\u0000 2 1 1 IdUser 1 2 IdGlobal # " + /* META_RESULT, 2 cols, type(0-char 1-num 2-date) [out_result name] */
"\u0000*/";


public static final String EP_QUERY_AC_SELECT_EVENT_INFO_BY_FORM =
/* SQL : 	SELECT I.ValChar, I.ValNum, I.ValDate, I.Position, E.IdGlobal IdEvent FROM Info I, Event E WHERE I.IdEvent = E.IdGlobal AND E.IdForm=? */
"/*EP \u0001 0 5 5 4 # 1 4 4 5 r0 4 1 0 1 0 2 3 # 8 3 3 4 0 r1 r2 r3 # 1 2 2 3 r4 1 3 1 32 # 4 1 1 2 32 0 ?1 r5 # 1 0 0 1 r0 5 4 1 42 43 44 45 40 # \u0000 5 0 7 ValChar 1 8 ValNum 2 9 ValDate 1 10 Position 1 11 IdEvent # \u0000*/";


public static final String EP_QUERY_AC_SELECT_EVENT_INFO_BY_FORM_AND_POSITION =
/* SQL : 	SELECT i.ValChar FROM Event e, Info i WHERE i.IdEvent = e.IdGlobal AND e.IdForm=? AND i.Position = ? */
"/*EP \u0002 0 6 6 4 # 1 5 5 6 r0 2 4 1 42 45 # 4 4 4 5 45 0 ?2 r2 # 1 3 3 4 r0 4 1 0 1 0 2 3 # 8 2 2 3 0 r4 r5 r6 # 1 1 1 2 r7 1 3 1 32 # 4 0 0 1 32 0 ?1 r8 # \u0000 1 0 1 ValChar # \u0000*/";


public static final String EP_QUERY_SELECT_USER_HABILITATION =
/* SQL : 	SELECT u.Nom, u.Prenom, u.Type, u.Tel, u.IdGlobal, h.IdRole FROM UserDMSP u, Habilitation h WHERE u.IdGlobal = h.IdUser */
"/*EP \u0000 " + 
"0 3 3 8 # " + /* SCAN, Table Habilitation (8) -->R0 */
"1 2 2 3 r0 1 2 0 1 # " + /* TABLE_LOOKUP pos:R0, 1 cols, skt SktHabili(2), is_table: 0  -->R1 - R1 */
"1 1 1 2 r1 5 2 1 14 19 15 23 10 # " + /* TABLE_LOOKUP pos:R1, 5 cols, table UserDMSP(2), is_table: 1	-->R2 - R6 */
"1 0 0 1 r0 1 8 1 62 # " + /* TABLE_LOOKUP pos:R0, 1 cols, table Habilitation(8), is_table: 1	-->R7 - R7 */
"\u0000 6 0 2 Nom 0 3 Prenom 1 4 Type 0 5 Tel 1 6 IdGlobal 1 7 IdRole # " + /* META_RESULT, 6 cols, type(0-char 1-num 2-date) [out_result name] */
"\u0000*/";


// ################ 
//  INSERT PLANS: # 
// ################ 

public static String OEP_EVENT_AC_INSERT = 
// TODO (DONE): replace IdGloal "?1" by numeroauto "v30", replace TSSanteos 0 with "v10", decrement numbering  of ?i   
/* SQL : 	INSERT INTO Event (Author, TSSPT, TSSanteos, IdForm, IdUser, IdEpisode, DateEvent, DateFin, Filtre) VALUES (?, ?, 0, ?, ?, ?, ?, ?, ?); */
"/*EP \u0008 " + 
"2 7 7 -1 1 ?3 # " + /* CI_LOOKUP ref_tab:Formulaire(1) key_col_id:5 ka_id:1	 key:?3(R0) -->R1 */
"2 8 8 -1 4 ?4 # " + /* CI_LOOKUP ref_tab:UserDMSP(2) key_col_id:10 ka_id:4	 key:?4(R2) -->R3 */
"7 6 6 7 8 # " + /* FLOW_X */
"2 9 9 -1 0 ?5 # " + /* CI_LOOKUP ref_tab:Episode(0) key_col_id:0 ka_id:0	 key:?5(R4) -->R5 */
"7 5 5 6 9 # " + /* FLOW_X */
"8 4 4 5 3 r3 r1 r5 # " + /* ACCESS_RIGHTS access_type: 3 (0-s,1-u,2-d,3-i) res_user:R3 res_form:R1 res_epis:R5 */
"6 3 3 4 2 ?3 # " + /* CI_INSERT ref_tab:Event(3), key_tab:Formulaire(1), col:IdGlobal(5), ka_id:2, key:?3(R6) */
"6 2 2 3 5 v30 # " + /* CI_INSERT ref_tab:Event(3), key_tab:Event(3), col:IdGlobal(28), ka_id:5, key:v30(R7) */
"5 1 1 2 3 0 0 0 r1 1 r3 2 r5 # " + /* TABLE_INSERT 3 cols, skt SktEvent(0), is_table: 0, [col_id value] */
"5 0 0 1 10 3 1 29 ?1 30 ?2 31 v10 32 ?3 33 ?4 34 ?5 35 ?6 95 ?7 96 ?8 28 r7 # " + /* TABLE_INSERT 10 cols, table Event(3), is_table: 1, [col_id value] */
"\u0000*/";


public static String OEP_INFO_AC_INSERT = 
// TODO (DONE): replace IdGloal "?1" by numeroauto "v30", replace TSSanteos 0 with "v10", decrement numbering  of ?i   
/* SQL : 	INSERT INTO Info (Author, TSSPT, TSSanteos, IdEvent, IdComment, ValChar, ValNum, ValDate, Position, Filtre, IdConcept) VALUES (?, ?, 0, ?, ?, ?, ?, ?, ?, ?, ?); */
"/*EP \n " + 
"2 8 8 -1 5 ?3 # " + /* CI_LOOKUP ref_tab:Event(3) key_col_id:28 ka_id:5	 key:?3(R0) -->R1 */
"1 7 7 8 r1 3 0 0 0 1 2 # " + /* TABLE_LOOKUP pos:R1, 3 cols, skt SktEvent(0), is_table: 0  -->R2 - R4 */
"8 6 6 7 3 r3 r2 r4 # " + /* ACCESS_RIGHTS access_type: 3 (0-s,1-u,2-d,3-i) res_user:R3 res_form:R2 res_epis:R4 */
"1 5 5 6 r2 1 1 1 5 # " + /* TABLE_LOOKUP pos:R2, 1 cols, table Formulaire(1), is_table: 1	-->R5 - R5 */
"2 9 9 -1 7 ?4 # " + /* CI_LOOKUP ref_tab:Comment(5) key_col_id:47 ka_id:7	 key:?4(R6) -->R7 */
"7 4 4 5 9 # " + /* FLOW_X */
"6 3 3 4 3 r5 # " + /* CI_INSERT ref_tab:Info(4), key_tab:Formulaire(1), col:IdGlobal(5), ka_id:3, key:R5 */
"6 2 2 3 6 v30 # " + /* CI_INSERT ref_tab:Info(4), key_tab:Info(4), col:IdGlobal(36), ka_id:6, key:v30(R8) */
"5 1 1 2 5 1 0 0 r2 1 r3 2 r4 3 r1 4 r7 # " + /* TABLE_INSERT 5 cols, skt SktInfo(1), is_table: 0, [col_id value] */
"5 0 0 1 12 4 1 37 ?1 38 ?2 39 v10 40 ?3 41 ?4 42 ?5 43 ?6 44 ?7 45 ?8 46 ?9 92 ?10 36 r8 # " + /* TABLE_INSERT 12 cols, table Info(4), is_table: 1, [col_id value] */
"\u0000*/";


public static String OEP_COMMENT_NOAC_INSERT = 
// TODO (DONE): replace IdGloal "?1" by numeroauto "v30", replace TSSanteos 0 with "v10", decrement numbering  of ?i   
/* SQL : 	INSERT INTO Comment (Author, TSSPT, TSSanteos, ValComment) VALUES (?, ?, 0, ?); */
"/*EP \u0003 " + 
"6 1 1 -1 7 v30 # " + /* CI_INSERT ref_tab:Comment(5), key_tab:Comment(5), col:IdGlobal(47), ka_id:7, key:v30(R0) */
"5 0 0 1 5 5 1 48 ?1 49 ?2 50 v10 51 ?3 47 r0 # " + /* TABLE_INSERT 5 cols, table Comment(5), is_table: 1, [col_id value] */
"\u0000*/";


public static String EP_HABILITATION_NOAC_INSERT = 
// TODO (DONE): replace IdGloal "?1" by numeroauto "v30", decrement numbering  of ?i   
/* SQL : 	INSERT INTO habilitation (Author, TSSPT, TSSanteos, IdRole, IdUSer) VALUES (?, ?, ?, ?, ?); */
"/*EP \u0005 " + 
"2 4 4 -1 8 ?4 # " + /* CI_LOOKUP ref_tab:Role(6) key_col_id:52 ka_id:8	 key:?4(R0) -->R1 */
"2 5 5 -1 4 ?5 # " + /* CI_LOOKUP ref_tab:UserDMSP(2) key_col_id:10 ka_id:4	 key:?5(R2) -->R3 */
"7 3 3 4 5 # " + /* FLOW_X */
"6 2 2 3 9 v30 # " + /* CI_INSERT ref_tab:Habilitation(8), key_tab:Habilitation(8), col:IdGlobal(57), ka_id:9, key:v30(R4) */
"5 1 1 2 2 2 0 0 r1 1 r3 # " + /* TABLE_INSERT 2 cols, skt SktHabili(2), is_table: 0, [col_id value] */
"5 0 0 1 6 8 1 58 ?1 59 ?2 60 ?3 62 ?4 63 ?5 57 r4 # " + /* TABLE_INSERT 6 cols, table Habilitation(8), is_table: 1, [col_id value] */
"\u0000*/";


public static String EP_DELETED_NOAC_INSERT =
/* SQL : 	INSERT INTO TupleDeleted (IdGlobal, TabId, Author, TSSPT, TSSanteos) VALUES (?, ?, ?, ?, ?); */
"/*EP \u0005 " + 
"5 0 0 -1 5 11 1 80 ?1 81 ?2 82 ?3 83 ?4 84 ?5 # " + /* TABLE_INSERT 5 cols, table TupleDeleted(11), is_table: 1, [col_id value] */
"\u0000*/";


// ################# 
//   UPDATE PLANS: # 
// ################# 

public static String INFO_AC_UPDATE_BY_ID = 
/* SQL : 	UPDATE Info SET TSSPT=?, ValChar=?, ValNum=?, ValDate=?, Filtre=? WHERE IdGlobal=?; */
"/*EP \u0006 " + 
"0 5 5 4 # " + /* SCAN, Table Info (4) -->R0 */
"1 4 4 5 r0 7 4 1 37 39 40 41 45 92 36 # " + /* TABLE_LOOKUP pos:R0, 7 cols, table Info(4), is_table: 1	-->R1 - R7 */
"4 3 3 4 36 0 ?6 r7 # " + /* SELECT, att: IdGlobal(36), comparator: 0, parameter: ?6 (R8), from pos: R7*/
"1 2 2 3 r0 3 1 0 1 0 2 # " + /* TABLE_LOOKUP pos:R0, 3 cols, skt SktInfo(1), is_table: 0  -->R9 - R11 */
"8 1 1 2 1 r9 r10 r11 # " + /* ACCESS_RIGHTS access_type: 1 (0-s,1-u,2-d,3-i) res_user:R9 res_form:R10 res_epis:R11 */
"a 0 0 1 12 4 r0 36 ?6 37 r1 38 ?1 39 r2 40 r3 41 r4 42 ?2 43 ?3 44 ?4 45 r5 46 ?5 92 r6 # " + /* TABLE UPDATE, 12 cols, Table Info(4), tuple pos: r0 [col_id res_id] */
"\u0000*/";


public static String COMMENT_AC_UPDATE_BY_ID = 
// AC UPDATE Comment SET TSSPT = ?, ValComment = ? WHERE IdGlobal = ?; 
//  --> would be generated by moulinette without AC 
//  TODO (DONE): do it by hand (see org.inria.dmsp.EP_UI)  
// Taken from org.inria.dmsp.EP_UI:
"/*EP \u0003 0 5 5 4 # " +	// scan of table info(4) --> r0 (infoPos)
"1 4 4 5 r0 4 1 0 0 1 2 4 # " +   // TABLE LOOKUP pos r0, 4 cols, SKTinfo(1), is SKT(0), 0 (formPos->5), 1 (userPos->10), 2 (episodePos->0), 3 (idComment->47) --> r1-r4
"8 3 3 4 1 r2 r1 r3 # " +         // access_type(0:read), in_res_UserDMSP(r2), in_res_Formulaire(r1), in_res_Episode(r3)
"1 2 2 3 r4 3 5 1 47 48 50 # " +   // TABLE LOOKUP pos r0, 3 cols, table comment (5), is table(1), All attribute except those updated --> r5-r7
"4 1 1 2 47 0 ?3 r5 # " +          // SELECT Col IdGlobal(47), is equal (0), to parameter 3, the value being in r1 --> r4
"a 0 0 1 5 5 r4 47 r5 48 r6 49 ?1 50 r7 51 ?2 # \u0000*/";
// TABLE UPDATE 5 cols, Table Comment(5), for tuple pos(R0), ColId, Ri
// params: 1=49(TSSPT), 2=51(ValComment), 3=47(IdG)

public static String EVENT_AC_UPDATE_BY_ID = 
/* SQL : 	UPDATE Event SET TSSPT = ?, DateEvent = ?, DateFin = ?, Filtre = ? WHERE IdGlobal = ?; */
"/*EP \u0005 " + 
"0 5 5 3 # " + /* SCAN, Table Event (3) -->R0 */
"1 4 4 5 r0 6 3 1 29 31 32 33 34 28 # " + /* TABLE_LOOKUP pos:R0, 6 cols, table Event(3), is_table: 1	-->R1 - R6 */
"4 3 3 4 28 0 ?5 r6 # " + /* SELECT, att: IdGlobal(28), comparator: 0, parameter: ?5 (R7), from pos: R6*/
"1 2 2 3 r0 3 0 0 1 0 2 # " + /* TABLE_LOOKUP pos:R0, 3 cols, skt SktEvent(0), is_table: 0  -->R8 - R10 */
"8 1 1 2 1 r8 r9 r10 # " + /* ACCESS_RIGHTS access_type: 1 (0-s,1-u,2-d,3-i) res_user:R8 res_form:R9 res_epis:R10 */
"a 0 0 1 10 3 r0 28 ?5 29 r1 30 ?1 31 r2 32 r3 33 r4 34 r5 35 ?2 95 ?3 96 ?4 # " + /* TABLE UPDATE, 10 cols, Table Event(3), tuple pos: r0 [col_id res_id] */
"\u0000*/";


// ################# 
//   DELETE PLANS: # 
// ################# 

public static String EP_HABILITATION_NOAC_DELETE_BY_USER = 
/* SQL : 	DELETE FROM Habilitation WHERE IdUser=?; */
"/*EP \u0001 " + 
"0 4 4 8 # " + /* SCAN, Table Habilitation (8) -->R0 */
"1 3 3 4 r0 2 8 1 57 63 # " + /* TABLE_LOOKUP pos:R0, 2 cols, table Habilitation(8), is_table: 1	-->R1 - R2 */
"4 2 2 3 63 0 ?1 r2 # " + /* SELECT, att: IdUser(63), comparator: 0, parameter: ?1 (R3), from pos: R2*/
"5 1 1 2 3 12 1 85 v18 86 r0 87 v10 # " + /* TABLE_INSERT 3 cols, table LogDeleted(12), is_table: 1, [col_id value] -->R4 - R5*/
"9 0 0 1 8 r0 # " + /* TABLE DELETE, table Habilitation(8), tuple pos: R0 */
"\u0000*/";


public static String EP_EVENT_AC_DELETE_BY_ID =
/* SQL : 	DELETE FROM Event WHERE idGlobal = ?; */
"/*EP \u0001 " + 
"0 6 6 3 # " + /* SCAN, Table Event (3) -->R0 */
"1 5 5 6 r0 1 3 1 28 # " + /* TABLE_LOOKUP pos:R0, 1 cols, table Event(3), is_table: 1	-->R1 - R1 */
"4 4 4 5 28 0 ?1 r1 # " + /* SELECT, att: IdGlobal(28), comparator: 0, parameter: ?1 (R2), from pos: R1*/
"1 3 3 4 r0 3 0 0 1 0 2 # " + /* TABLE_LOOKUP pos:R0, 3 cols, skt SktEvent(0), is_table: 0  -->R3 - R5 */
"8 2 2 3 1 r3 r4 r5 # " + /* ACCESS_RIGHTS access_type: 1 (0-s,1-u,2-d,3-i) res_user:R3 res_form:R4 res_epis:R5 */
"5 1 1 2 3 12 1 85 v13 86 r0 87 v10 # " + /* TABLE_INSERT 3 cols, table LogDeleted(12), is_table: 1, [col_id value] -->R6 - R7*/
"9 0 0 1 3 r0 # " + /* TABLE DELETE, table Event(3), tuple pos: R0 */
"\u0000*/";


public static final String EP_INFO_AC_DELETE_BY_EVENT =
/* SQL : 	DELETE FROM Info WHERE IdEvent = ? */
"/*EP \u0001 " + 
"0 6 6 4 # " + /* SCAN, Table Info (4) -->R0 */
"1 5 5 6 r0 2 4 1 36 40 # " + /* TABLE_LOOKUP pos:R0, 2 cols, table Info(4), is_table: 1	-->R1 - R2 */
"4 4 4 5 40 0 ?1 r2 # " + /* SELECT, att: IdEvent(40), comparator: 0, parameter: ?1 (R3), from pos: R2*/
"1 3 3 4 r0 3 1 0 1 0 2 # " + /* TABLE_LOOKUP pos:R0, 3 cols, skt SktInfo(1), is_table: 0  -->R4 - R6 */
"8 2 2 3 1 r4 r5 r6 # " + /* ACCESS_RIGHTS access_type: 1 (0-s,1-u,2-d,3-i) res_user:R4 res_form:R5 res_epis:R6 */
"5 1 1 2 3 12 1 85 v14 86 r0 87 v10 # " + /* TABLE_INSERT 3 cols, table LogDeleted(12), is_table: 1, [col_id value] -->R7 - R8*/
"9 0 0 1 4 r0 # " + /* TABLE DELETE, table Info(4), tuple pos: R0 */
"\u0000*/";


public static String EP_INFO_AC_DELETE_BY_ID =
/* SQL : 	DELETE FROM Info WHERE IdGlobal = ?; */
"/*EP \u0001 " + 
"0 6 6 4 # " + /* SCAN, Table Info (4) -->R0 */
"1 5 5 6 r0 1 4 1 36 # " + /* TABLE_LOOKUP pos:R0, 1 cols, table Info(4), is_table: 1	-->R1 - R1 */
"4 4 4 5 36 0 ?1 r1 # " + /* SELECT, att: IdGlobal(36), comparator: 0, parameter: ?1 (R2), from pos: R1*/
"1 3 3 4 r0 3 1 0 1 0 2 # " + /* TABLE_LOOKUP pos:R0, 3 cols, skt SktInfo(1), is_table: 0  -->R3 - R5 */
"8 2 2 3 1 r3 r4 r5 # " + /* ACCESS_RIGHTS access_type: 1 (0-s,1-u,2-d,3-i) res_user:R3 res_form:R4 res_epis:R5 */
"5 1 1 2 3 12 1 85 v14 86 r0 87 v10 # " + /* TABLE_INSERT 3 cols, table LogDeleted(12), is_table: 1, [col_id value] -->R6 - R7*/
"9 0 0 1 4 r0 # " + /* TABLE DELETE, table Info(4), tuple pos: R0 */
"\u0000*/";


public static final String EP_QUERY_SELECT_NOAC_INFO_BY_EVENT = 
/* SQL : 	SELECT IdGlobal FROM Info WHERE IdEvent = ? */
"/*EP \u0001 " + 
"0 2 2 4 # " + /* SCAN, Table Info (4) -->R0 */
"1 1 1 2 r0 2 4 1 36 40 # " + /* TABLE_LOOKUP pos:R0, 2 cols, table Info(4), is_table: 1	-->R1 - R2 */
"4 0 0 1 40 0 ?1 r2 # " + /* SELECT, att: IdEvent(40), comparator: 0, parameter: ?1 (R3), from pos: R2*/
"\u0000 1 1 1 IdGlobal # " + /* META_RESULT, 1 cols, type(0-char 1-num 2-date) [out_result name] */
"\u0000*/";


public static final String EP_QUERY_NOAC_SELECT_BY_ID =
/* SQL : 	SELECT Nom, Prenom FROM UserDMSP u WHERE u.idGlobal = ? */
"/*EP \u0001 " + 
"2 1 1 -1 4 ?1 # " + /* CI_LOOKUP ref_tab:UserDMSP(2) key_col_id:10 ka_id:4	 key:?1(R0) -->R1 */
"1 0 0 1 r1 2 2 1 14 19 # " + /* TABLE_LOOKUP pos:R1, 2 cols, table UserDMSP(2), is_table: 1	-->R2 - R3 */
"\u0000 2 0 2 Nom 0 3 Prenom # " + /* META_RESULT, 2 cols, type(0-char 1-num 2-date) [out_result name] */
"\u0000*/";


public static final String EP_QUERY_SELECT_EVENT_INFO_BY_EVENT_AND_FILTRE =
/* SQL : 	SELECT ValChar, Position FROM Info WHERE IdEvent = ? AND Filtre = ? */
"/*EP \u0002 " + 
"0 3 3 4 # " + /* SCAN, Table Info (4) -->R0 */
"1 2 2 3 r0 4 4 1 42 45 40 46 # " + /* TABLE_LOOKUP pos:R0, 4 cols, table Info(4), is_table: 1	-->R1 - R4 */
"4 1 1 2 40 0 ?1 r3 # " + /* SELECT, att: IdEvent(40), comparator: 0, parameter: ?1 (R5), from pos: R3*/
"4 0 0 1 46 0 ?2 r4 # " + /* SELECT, att: Filtre(46), comparator: 0, parameter: ?2 (R6), from pos: R4*/
"\u0000 2 0 1 ValChar 1 2 Position # " + /* META_RESULT, 2 cols, type(0-char 1-num 2-date) [out_result name] */
"\u0000*/";


public static final String EP_QUERY_AC_SELECT_EVENT_INFO_BY_EVENT_AND_POSITION =
/* SQL : 	SELECT ValNum FROM Info WHERE IdEvent = ? AND Position = ? */
"/*EP \u0002 " + 
"0 5 5 4 # " + /* SCAN, Table Info (4) -->R0 */
"1 4 4 5 r0 3 4 1 43 40 45 # " + /* TABLE_LOOKUP pos:R0, 3 cols, table Info(4), is_table: 1	-->R1 - R3 */
"4 3 3 4 40 0 ?1 r2 # " + /* SELECT, att: IdEvent(40), comparator: 0, parameter: ?1 (R4), from pos: R2*/
"4 2 2 3 45 0 ?2 r3 # " + /* SELECT, att: Position(45), comparator: 0, parameter: ?2 (R5), from pos: R3*/
"1 1 1 2 r0 3 1 0 1 0 2 # " + /* TABLE_LOOKUP pos:R0, 3 cols, skt SktInfo(1), is_table: 0  -->R6 - R8 */
"8 0 0 1 0 r6 r7 r8 # " + /* ACCESS_RIGHTS access_type: 0 (0-s,1-u,2-d,3-i) res_user:R6 res_form:R7 res_epis:R8 */
"\u0000 1 1 1 ValNum # " + /* META_RESULT, 1 cols, type(0-char 1-num 2-date) [out_result name] */
"\u0000*/";


} 
